### ISSUE TITLE
These lines of code seem to be redundant, can I delete the code from line 47 to line 50？

### ISSUE THREAD

**Issue by chenjiadong96** [swathikirans/GSM#12]
https://github.com/swathikirans/GSM/blob/43e8ebad5cf1bf2aaca1674a753a89fcba416321/gsm.py#L47
These lines of code seem to be redundant, can I delete the code from line 47 to line 50？ 
In other words, do these few lines of code have a special purpose?

**Comment by swathikirans** [comment]
These lines perform channel shuffling. If you are planning to use the pre-trained models, then you will have to keep these lines. Otherwise you may remove them (i.e., if you are training a new model).

**Comment by chenjiadong96** [comment]
If the channel shuffle operation is not added, will it affect the training accuracy? It seems that there is no order relationship between the channels, why need to shuffle?

**Comment by swathikirans** [comment]
Hi, this shuffling operation simply acts as a regularization. I don't think it will have great impact on the final performance of the model. You can train the model without these operations.

**Comment by chenjiadong96** [comment]
Thanks for your reply.😉
