### ISSUE TITLE
Different dimension in figure 2 and figure 3 in  your paper

### ISSUE THREAD

**Issue by zyy-student** [swathikirans/GSM#19]
In your paper, you show your GSM design in Figure 2 with a component "1*3*3 convolutions". However, in Figure 3, you show your GSM implementation with a component "3*3*3 convolutions". Why? Does that mean I need to do 3D convolutions in GSM?

**Comment by swathikirans** [comment]
The 2D convolution shown in Fig. 2 is part of the backbone network. The 3D convolution in Fig. 3 is part of the gating mechanism in GSM. The 3D convolution outputs a single feature plane and is used to select the features for routing. This is not the same as 3D convolutions in 3D CNNs where the 3D convolution performs spatio-temporal feature extraction.

**Comment by zyy-student** [comment]
OK, I get that. Thanks.
