### ISSUE TITLE
How to get the result in Tab 3

### ISSUE THREAD

**Issue by zyy-student** [swathikirans/GSM#20]
In your paper, you show the result on something-v1 dataset in Tab 3. How to get them. Do I need to train 4 models with different segment parameter (8, 12, 16, 24)?

**Comment by swathikirans** [comment]
Hi,

The ensemble result reported in Tab. 3 is obtained by averaging the scores of the individual models. Thus, you need to train four different models with segments=8, 12, 16 and 24.

**Comment by zyy-student** [comment]
So, the 8 * 2 means testing a model which is trained with segments = 8. Is that right? And in your paper, you describe the 2 in 8*2 as clips. What does the 2 mean specifically. Two different video in dataset?

**Comment by swathikirans** [comment]
Yes, 8x2 in Tab. 3 shows the result obtained from a model trained with 8 segments. 8x2 means 2 clips, each consisting of 8 frames, are extracted from each video during inference. The scores obtained from the 2 clips are averaged to obtain the final prediction for each video.

**Comment by zyy-student** [comment]
OK. But why do you show the averaging scores of different test. Why not just show the different result respectively. It is a little strange.

**Comment by swathikirans** [comment]
Sorry, I did not get your question.

**Comment by zyy-student** [comment]
For example, you can show the score of 8 * 2 frames, the score of 12 * 2 frames, the score of 16 frames and the score of 24 frames separately. Why do you show the averaging score like 8×2+12×2+16+24?

**Comment by swathikirans** [comment]
It is the score obtained from an ensemble of models trained with different number of frames. Please see Tab. 3 in the supplementary document or Tab. 8 in the arXiv version for the scores obtained from individual models.

**Comment by zyy-student** [comment]
OK, I get that! Thanks a lot.
