### ISSUE TITLE
RuntimeError: invalid argument 2 while testing

### ISSUE THREAD

**Issue by avijit9** [swathikirans/GSM#4]
While testing the model after training, I'm getting the following error:

`RuntimeError: invalid argument 2: size '[0 x 16 x 64 x 27 x 27]' is invalid for input with 186624 elements at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/TH/THStorage.cpp:84`

Do you have any idea to fix this?

**Comment by swathikirans** [comment]
Please set the number of GPUs to 1 during testing.
