### ISSUE TITLE
Run model on Input Video

### ISSUE THREAD

**Issue by NaeemKhan333** [swathikirans/GSM#5]
Thanks for nice work. Can you provide the inference script for running the model on the input Video. Thanks

**Comment by NaeemKhan333** [comment]
I have trained my own data set ,using the something-something data set format.Please provide me the code for testing the model on the input video. Thank you

**Comment by swathikirans** [comment]
Please check [test_models.py](https://github.com/swathikirans/GSM/blob/master/test_models.py) for inference.

**Comment by NaeemKhan333** [comment]
How to run on webcam?

**Comment by NaeemKhan333** [comment]
I have got following accuracy
Class Accuracy 36.67%
Overall Prec@1 36.67% Prec@5 100.00%

**Comment by swathikirans** [comment]
It is not implemented. You can refer to this repo for video level inference from webcam
https://github.com/metalbubble/TRN-pytorch

**Comment by NaeemKhan333** [comment]
I have to do any changing because you have changed the network?
