### ISSUE TITLE
pretrained models download failed 

### ISSUE THREAD

**Issue by AliceCrystal** [swathikirans/GSM#7]
How can I download these pretrained models

**Comment by swathikirans** [comment]
The models can be downloaded by running `python download_models.py`.

**Comment by AliceCrystal** [comment]
I had tried to run "python download_models.py",  but when run the line 
`response = session.get(URL, params = {'id' : id}, stream = True)`
there are some errors:
`TimeoutError: [Errno 60] Operation timed out`

**Comment by swathikirans** [comment]
It seems to be some issue with the Google Drive API. You can download the models from here:
https://drive.google.com/open?id=1gCyshHmtgyPK5JhNH-1eY1iqhPaL_0WS
