### ISSUE TITLE
share the Visualization code with us

### ISSUE THREAD

**Issue by zgyangleo** [swathikirans/GSM#8]
could you share the visualization code with me?thanks.

**Comment by Zhuysheng** [comment]
How to visualize with t-SNE?

**Comment by swathikirans** [comment]
@zgyangleo You can refer to the following repo for the visualization
https://github.com/alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions

**Comment by swathikirans** [comment]
@Zhuysheng I used the the t-sne implementation in sklearn. Use the output from the backbone (https://github.com/swathikirans/GSM/blob/master/models.py#L194) as features.

**Comment by zgyangleo** [comment]
> @zgyangleo You can refer to the following repo for the visualization
> https://github.com/alexandrosstergiou/Saliency-Tubes-Visual-Explanations-for-Spatio-Temporal-Convolutions

Hi, in the visualization code, how to get the last convolution output from the GSM model, the shape I extracted from base_out is (8, 2048). Thanks very much. Could you share this part of code with me?
